name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint (basic import check)
        run: |
          python -c "import sys; import importlib; [importlib.import_module(m) for m in ['fastapi','uvicorn','tensorflow','pandas','numpy','sklearn','nltk']] or sys.exit(0)"
